INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Другое');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Республика Адыгея (Адыгея)');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Республика Башкортостан');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Республика Бурятия');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Республика Алтай');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Республика Дагестан');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Республика Ингушетия');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Кабардино-Балкарская Республика');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Республика Калмыкия');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Карачаево-Черкесская Республика');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Республика Карелия');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Республика Коми');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Республика Марий Эл');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Республика Мордовия');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Республика Саха (Якутия)');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Республика Северная Осетия — Алания');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Республика Татарстан (Татарстан)');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Республика Тыва');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Удмуртская Республика');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Республика Хакасия');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Чеченская Республика');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Чувашская Республика — Чувашия');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Алтайский край');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Краснодарский край');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Красноярский край');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Приморский край');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Ставропольский край');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Хабаровский край');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Амурская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Архангельская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Астраханская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Белгородская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Брянская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Владимирская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Волгоградская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Вологодская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Воронежская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Ивановская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Иркутская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Калининградская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Калужская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Камчатский край');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Кемеровская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Кировская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Костромская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Курганская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Курская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Ленинградская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Липецкая область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Магаданская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Московская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Мурманская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Нижегородская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Новгородская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Новосибирская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Омская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Оренбургская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Орловская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Пензенская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Пермский край');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Псковская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Ростовская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Рязанская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Самарская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Саратовская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Сахалинская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Свердловская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Смоленская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Тамбовская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Тверская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Томская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Тульская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Тюменская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Ульяновская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Челябинская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Забайкальский край');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Ярославская область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Город Москва');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Санкт-Петербург');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Еврейская автономная область');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Ненецкий автономный округ');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Ханты-Мансийский автономный округ — Югра');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Чукотский автономный округ');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Ямало-Ненецкий автономный округ');
INSERT INTO registration_region (id, name) VALUES (nextval('registration_region_id_seq'), 'Байконур');